//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace qwer.Date_Base
{
    using System;
    using System.Collections.Generic;
    using System.Windows.Media.Imaging;

    public partial class Pitanie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pitanie()
        {
            this.Zakazpit = new HashSet<Zakazpit>();
        }
        public BitmapImage PathImg
        {
            get
            {
                return new BitmapImage(new Uri("/Images/" + Фото, UriKind.Relative));
            }
        }

        public int CountProductOrder { get; set; }
        public int ID { get; set; }
        public string Фото { get; set; }
        public string Наименование_товара { get; set; }
        public string Описание_товара { get; set; }
        public Nullable<int> Производитель { get; set; }
        public string Цена { get; set; }
        public string Размер_скидки { get; set; }
        public string Количество { get; set; }
    
        public virtual Proizvoditel Proizvoditel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zakazpit> Zakazpit { get; set; }
    }
}
